import 'dart:convert';

import '../../../fem/model/fem_model_single_fem.dart';

class EstudioSolReg {
  int year = 2020;
  String id;
  String estado;
  String estdespacho;
  String tipo;
  String fechainicial;
  String fechacambio;
  String fechasolicitud;
  String unidad;
  String codigo;
  String proyecto;
  String circuito;
  String pm;
  String solicitante;
  String pdi;
  String wbe;
  String proyectowbe;
  String comentario1;
  String comentario2;
  String e4e;
  String descripcion;
  String um;
  String m01q1;
  String m01q2;
  String m01qx;
  String m02q1;
  String m02q2;
  String m02qx;
  String m03q1;
  String m03q2;
  String m03qx;
  String m04q1;
  String m04q2;
  String m04qx;
  String m05q1;
  String m05q2;
  String m05qx;
  String m06q1;
  String m06q2;
  String m06qx;
  String m07q1;
  String m07q2;
  String m07qx;
  String m08q1;
  String m08q2;
  String m08qx;
  String m09q1;
  String m09q2;
  String m09qx;
  String m10q1;
  String m10q2;
  String m10qx;
  String m11q1;
  String m11q2;
  String m11qx;
  String m12q1;
  String m12q2;
  String m12qx;
  String cambio;
  String razon;
  String persona;
  String fecha;
  String respuesta;
  String razonrespuesta;
  String personarespuesta;
  String fecharespuesta;
  EstudioSolReg({
    required this.id,
    required this.estado,
    required this.estdespacho,
    required this.tipo,
    required this.fechainicial,
    required this.fechacambio,
    required this.fechasolicitud,
    required this.unidad,
    required this.codigo,
    required this.proyecto,
    required this.circuito,
    required this.pm,
    required this.solicitante,
    required this.pdi,
    required this.wbe,
    required this.proyectowbe,
    required this.comentario1,
    required this.comentario2,
    required this.e4e,
    required this.descripcion,
    required this.um,
    required this.m01q1,
    required this.m01q2,
    required this.m01qx,
    required this.m02q1,
    required this.m02q2,
    required this.m02qx,
    required this.m03q1,
    required this.m03q2,
    required this.m03qx,
    required this.m04q1,
    required this.m04q2,
    required this.m04qx,
    required this.m05q1,
    required this.m05q2,
    required this.m05qx,
    required this.m06q1,
    required this.m06q2,
    required this.m06qx,
    required this.m07q1,
    required this.m07q2,
    required this.m07qx,
    required this.m08q1,
    required this.m08q2,
    required this.m08qx,
    required this.m09q1,
    required this.m09q2,
    required this.m09qx,
    required this.m10q1,
    required this.m10q2,
    required this.m10qx,
    required this.m11q1,
    required this.m11q2,
    required this.m11qx,
    required this.m12q1,
    required this.m12q2,
    required this.m12qx,
    required this.cambio,
    required this.razon,
    required this.persona,
    required this.fecha,
    required this.respuesta,
    required this.razonrespuesta,
    required this.personarespuesta,
    required this.fecharespuesta,
  });

  List<String> toList() {
    return [
      id,
      estado,
      estdespacho,
      tipo,
      fechainicial,
      fechacambio,
      fechasolicitud,
      unidad,
      codigo,
      proyecto,
      circuito,
      pm,
      solicitante,
      pdi,
      wbe,
      proyectowbe,
      comentario1,
      comentario2,
      e4e,
      descripcion,
      um,
      m01q1,
      m01q2,
      m01qx,
      m02q1,
      m02q2,
      m02qx,
      m03q1,
      m03q2,
      m03qx,
      m04q1,
      m04q2,
      m04qx,
      m05q1,
      m05q2,
      m05qx,
      m06q1,
      m06q2,
      m06qx,
      m07q1,
      m07q2,
      m07qx,
      m08q1,
      m08q2,
      m08qx,
      m09q1,
      m09q2,
      m09qx,
      m10q1,
      m10q2,
      m10qx,
      m11q1,
      m11q2,
      m11qx,
      m12q1,
      m12q2,
      m12qx,
      cambio,
      razon,
      persona,
      fecha,
      respuesta,
      razonrespuesta,
      personarespuesta,
      fecharespuesta,
    ];
  }

  EstudioSolReg copyWith({
    String? id,
    String? estado,
    String? estdespacho,
    String? tipo,
    String? fechainicial,
    String? fechacambio,
    String? fechasolicitud,
    String? unidad,
    String? codigo,
    String? proyecto,
    String? circuito,
    String? pm,
    String? solicitante,
    String? pdi,
    String? wbe,
    String? proyectowbe,
    String? comentario1,
    String? comentario2,
    String? e4e,
    String? descripcion,
    String? um,
    String? m01q1,
    String? m01q2,
    String? m01qx,
    String? m02q1,
    String? m02q2,
    String? m02qx,
    String? m03q1,
    String? m03q2,
    String? m03qx,
    String? m04q1,
    String? m04q2,
    String? m04qx,
    String? m05q1,
    String? m05q2,
    String? m05qx,
    String? m06q1,
    String? m06q2,
    String? m06qx,
    String? m07q1,
    String? m07q2,
    String? m07qx,
    String? m08q1,
    String? m08q2,
    String? m08qx,
    String? m09q1,
    String? m09q2,
    String? m09qx,
    String? m10q1,
    String? m10q2,
    String? m10qx,
    String? m11q1,
    String? m11q2,
    String? m11qx,
    String? m12q1,
    String? m12q2,
    String? m12qx,
    String? cambio,
    String? razon,
    String? persona,
    String? fecha,
    String? respuesta,
    String? razonrespuesta,
    String? personarespuesta,
    String? fecharespuesta,
  }) {
    return EstudioSolReg(
      id: id ?? this.id,
      estado: estado ?? this.estado,
      estdespacho: estdespacho ?? this.estdespacho,
      tipo: tipo ?? this.tipo,
      fechainicial: fechainicial ?? this.fechainicial,
      fechacambio: fechacambio ?? this.fechacambio,
      fechasolicitud: fechasolicitud ?? this.fechasolicitud,
      unidad: unidad ?? this.unidad,
      codigo: codigo ?? this.codigo,
      proyecto: proyecto ?? this.proyecto,
      circuito: circuito ?? this.circuito,
      pm: pm ?? this.pm,
      solicitante: solicitante ?? this.solicitante,
      pdi: pdi ?? this.pdi,
      wbe: wbe ?? this.wbe,
      proyectowbe: proyectowbe ?? this.proyectowbe,
      comentario1: comentario1 ?? this.comentario1,
      comentario2: comentario2 ?? this.comentario2,
      e4e: e4e ?? this.e4e,
      descripcion: descripcion ?? this.descripcion,
      um: um ?? this.um,
      m01q1: m01q1 ?? this.m01q1,
      m01q2: m01q2 ?? this.m01q2,
      m01qx: m01qx ?? this.m01qx,
      m02q1: m02q1 ?? this.m02q1,
      m02q2: m02q2 ?? this.m02q2,
      m02qx: m02qx ?? this.m02qx,
      m03q1: m03q1 ?? this.m03q1,
      m03q2: m03q2 ?? this.m03q2,
      m03qx: m03qx ?? this.m03qx,
      m04q1: m04q1 ?? this.m04q1,
      m04q2: m04q2 ?? this.m04q2,
      m04qx: m04qx ?? this.m04qx,
      m05q1: m05q1 ?? this.m05q1,
      m05q2: m05q2 ?? this.m05q2,
      m05qx: m05qx ?? this.m05qx,
      m06q1: m06q1 ?? this.m06q1,
      m06q2: m06q2 ?? this.m06q2,
      m06qx: m06qx ?? this.m06qx,
      m07q1: m07q1 ?? this.m07q1,
      m07q2: m07q2 ?? this.m07q2,
      m07qx: m07qx ?? this.m07qx,
      m08q1: m08q1 ?? this.m08q1,
      m08q2: m08q2 ?? this.m08q2,
      m08qx: m08qx ?? this.m08qx,
      m09q1: m09q1 ?? this.m09q1,
      m09q2: m09q2 ?? this.m09q2,
      m09qx: m09qx ?? this.m09qx,
      m10q1: m10q1 ?? this.m10q1,
      m10q2: m10q2 ?? this.m10q2,
      m10qx: m10qx ?? this.m10qx,
      m11q1: m11q1 ?? this.m11q1,
      m11q2: m11q2 ?? this.m11q2,
      m11qx: m11qx ?? this.m11qx,
      m12q1: m12q1 ?? this.m12q1,
      m12q2: m12q2 ?? this.m12q2,
      m12qx: m12qx ?? this.m12qx,
      cambio: cambio ?? this.cambio,
      razon: razon ?? this.razon,
      persona: persona ?? this.persona,
      fecha: fecha ?? this.fecha,
      respuesta: respuesta ?? this.respuesta,
      razonrespuesta: razonrespuesta ?? this.razonrespuesta,
      personarespuesta: personarespuesta ?? this.personarespuesta,
      fecharespuesta: fecharespuesta ?? this.fecharespuesta,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'año': '$year',
      'id': id,
      'estado': estado,
      'estdespacho': estdespacho,
      'tipo': tipo,
      'fechainicial': fechainicial,
      'fechacambio': fechacambio,
      'fechasolicitud': fechasolicitud,
      'unidad': unidad,
      'codigo': codigo,
      'proyecto': proyecto,
      'circuito': circuito,
      'pm': pm,
      'solicitante': solicitante,
      'pdi': pdi,
      'wbe': wbe,
      'proyectowbe': proyectowbe,
      'comentario1': comentario1,
      'comentario2': comentario2,
      'e4e': e4e,
      'descripcion': descripcion,
      'um': um,
      'm01q1': m01q1,
      'm01q2': m01q2,
      'm01qx': m01qx,
      'm02q1': m02q1,
      'm02q2': m02q2,
      'm02qx': m02qx,
      'm03q1': m03q1,
      'm03q2': m03q2,
      'm03qx': m03qx,
      'm04q1': m04q1,
      'm04q2': m04q2,
      'm04qx': m04qx,
      'm05q1': m05q1,
      'm05q2': m05q2,
      'm05qx': m05qx,
      'm06q1': m06q1,
      'm06q2': m06q2,
      'm06qx': m06qx,
      'm07q1': m07q1,
      'm07q2': m07q2,
      'm07qx': m07qx,
      'm08q1': m08q1,
      'm08q2': m08q2,
      'm08qx': m08qx,
      'm09q1': m09q1,
      'm09q2': m09q2,
      'm09qx': m09qx,
      'm10q1': m10q1,
      'm10q2': m10q2,
      'm10qx': m10qx,
      'm11q1': m11q1,
      'm11q2': m11q2,
      'm11qx': m11qx,
      'm12q1': m12q1,
      'm12q2': m12q2,
      'm12qx': m12qx,
      'cambio': cambio,
      'razon': razon,
      'persona': persona,
      'fecha': fecha,
      'respuesta': respuesta,
      'razonrespuesta': razonrespuesta,
      'personarespuesta': personarespuesta,
      'fecharespuesta': fecharespuesta,
    };
  }

  factory EstudioSolReg.fromMap(Map<String, dynamic> map) {
    return EstudioSolReg(
      id: map['id'].toString(),
      estado: map['estado'].toString(),
      estdespacho: map['estdespacho'].toString(),
      tipo: map['tipo'].toString(),
      fechainicial: map['fechainicial'].toString(),
      fechacambio: map['fechacambio'].toString(),
      fechasolicitud: map['fechasolicitud'].toString(),
      unidad: map['unidad'].toString(),
      codigo: map['codigo'].toString(),
      proyecto: map['proyecto'].toString(),
      circuito: map['circuito'].toString(),
      pm: map['pm'].toString(),
      solicitante: map['solicitante'].toString(),
      pdi: map['pdi'].toString(),
      wbe: map['wbe'].toString(),
      proyectowbe: map['proyectowbe'].toString(),
      comentario1: map['comentario1'].toString(),
      comentario2: map['comentario2'].toString(),
      e4e: map['e4e'].toString(),
      descripcion: map['descripcion'].toString(),
      um: map['um'].toString(),
      m01q1: map['m01q1'].toString(),
      m01q2: map['m01q2'].toString(),
      m01qx: map['m01qx'].toString(),
      m02q1: map['m02q1'].toString(),
      m02q2: map['m02q2'].toString(),
      m02qx: map['m02qx'].toString(),
      m03q1: map['m03q1'].toString(),
      m03q2: map['m03q2'].toString(),
      m03qx: map['m03qx'].toString(),
      m04q1: map['m04q1'].toString(),
      m04q2: map['m04q2'].toString(),
      m04qx: map['m04qx'].toString(),
      m05q1: map['m05q1'].toString(),
      m05q2: map['m05q2'].toString(),
      m05qx: map['m05qx'].toString(),
      m06q1: map['m06q1'].toString(),
      m06q2: map['m06q2'].toString(),
      m06qx: map['m06qx'].toString(),
      m07q1: map['m07q1'].toString(),
      m07q2: map['m07q2'].toString(),
      m07qx: map['m07qx'].toString(),
      m08q1: map['m08q1'].toString(),
      m08q2: map['m08q2'].toString(),
      m08qx: map['m08qx'].toString(),
      m09q1: map['m09q1'].toString(),
      m09q2: map['m09q2'].toString(),
      m09qx: map['m09qx'].toString(),
      m10q1: map['m10q1'].toString(),
      m10q2: map['m10q2'].toString(),
      m10qx: map['m10qx'].toString(),
      m11q1: map['m11q1'].toString(),
      m11q2: map['m11q2'].toString(),
      m11qx: map['m11qx'].toString(),
      m12q1: map['m12q1'].toString(),
      m12q2: map['m12q2'].toString(),
      m12qx: map['m12qx'].toString(),
      cambio: map['cambio'].toString(),
      razon: map['razon'].toString(),
      persona: map['persona'].toString(),
      fecha: map['fecha'].toString(),
      respuesta: map['respuesta'].toString(),
      razonrespuesta: map['razonrespuesta'].toString(),
      personarespuesta: map['personarespuesta'].toString(),
      fecharespuesta: map['fecharespuesta'].toString(),
    );
  }

  factory EstudioSolReg.fromSingleFEM(SingleFEM fem) {
    return EstudioSolReg(
      id: fem.id,
      estado: fem.estado,
      estdespacho: fem.estdespacho,
      tipo: fem.tipo,
      fechainicial: fem.fechainicial,
      fechacambio: fem.fechacambio,
      fechasolicitud: fem.fechasolicitud,
      unidad: fem.unidad,
      codigo: fem.codigo,
      proyecto: fem.proyecto,
      circuito: fem.circuito,
      pm: fem.pm,
      solicitante: fem.solicitante,
      pdi: fem.pdi,
      wbe: fem.wbe,
      proyectowbe: fem.proyectowbe,
      comentario1: fem.comentario1,
      comentario2: fem.comentario2,
      e4e: fem.e4e,
      descripcion: fem.descripcion,
      um: fem.um,
      m01q1: fem.m01q1,
      m01q2: fem.m01q2,
      m01qx: fem.m01qx,
      m02q1: fem.m02q1,
      m02q2: fem.m02q2,
      m02qx: fem.m02qx,
      m03q1: fem.m03q1,
      m03q2: fem.m03q2,
      m03qx: fem.m03qx,
      m04q1: fem.m04q1,
      m04q2: fem.m04q2,
      m04qx: fem.m04qx,
      m05q1: fem.m05q1,
      m05q2: fem.m05q2,
      m05qx: fem.m05qx,
      m06q1: fem.m06q1,
      m06q2: fem.m06q2,
      m06qx: fem.m06qx,
      m07q1: fem.m07q1,
      m07q2: fem.m07q2,
      m07qx: fem.m07qx,
      m08q1: fem.m08q1,
      m08q2: fem.m08q2,
      m08qx: fem.m08qx,
      m09q1: fem.m09q1,
      m09q2: fem.m09q2,
      m09qx: fem.m09qx,
      m10q1: fem.m10q1,
      m10q2: fem.m10q2,
      m10qx: fem.m10qx,
      m11q1: fem.m11q1,
      m11q2: fem.m11q2,
      m11qx: fem.m11qx,
      m12q1: fem.m12q1,
      m12q2: fem.m12q2,
      m12qx: fem.m12qx,
      cambio: '',
      razon: '',
      persona: '',
      fecha: '',
      respuesta: '',
      razonrespuesta: '',
      personarespuesta: '',
      fecharespuesta: '',
    );
  }

  String toJson() => json.encode(toMap());

  factory EstudioSolReg.fromJson(String source) =>
      EstudioSolReg.fromMap(json.decode(source));

  @override
  String toString() {
    return 'EstudioSolReg(id: $id, estado: $estado, estdespacho: $estdespacho, tipo: $tipo, fechainicial: $fechainicial, fechacambio: $fechacambio, fechasolicitud: $fechasolicitud, unidad: $unidad, codigo: $codigo, proyecto: $proyecto, circuito: $circuito, pm: $pm, solicitante: $solicitante, pdi: $pdi, wbe: $wbe, proyectowbe: $proyectowbe, comentario1: $comentario1, comentario2: $comentario2, e4e: $e4e, descripcion: $descripcion, um: $um, m01q1: $m01q1, m01q2: $m01q2, m01qx: $m01qx, m02q1: $m02q1, m02q2: $m02q2, m02qx: $m02qx, m03q1: $m03q1, m03q2: $m03q2, m03qx: $m03qx, m04q1: $m04q1, m04q2: $m04q2, m04qx: $m04qx, m05q1: $m05q1, m05q2: $m05q2, m05qx: $m05qx, m06q1: $m06q1, m06q2: $m06q2, m06qx: $m06qx, m07q1: $m07q1, m07q2: $m07q2, m07qx: $m07qx, m08q1: $m08q1, m08q2: $m08q2, m08qx: $m08qx, m09q1: $m09q1, m09q2: $m09q2, m09qx: $m09qx, m10q1: $m10q1, m10q2: $m10q2, m10qx: $m10qx, m11q1: $m11q1, m11q2: $m11q2, m11qx: $m11qx, m12q1: $m12q1, m12q2: $m12q2, m12qx: $m12qx, cambio: $cambio, razon: $razon, persona: $persona, fecha: $fecha, respuesta: $respuesta, razonrespuesta: $razonrespuesta, personarespuesta: $personarespuesta, fecharespuesta: $fecharespuesta)';
  }
}
