import 'package:fem_app/ficha/ficha_eliminados/model/ficha_eliminados_single_model.dart';

class SolicitadoSingle extends EliminadosSingle {
  SolicitadoSingle({
    required super.id,
    required super.estado,
    required super.estdespacho,
    required super.tipo,
    required super.fechainicial,
    required super.fechacambio,
    required super.fechasolicitud,
    required super.unidad,
    required super.codigo,
    required super.proyecto,
    required super.circuito,
    required super.pm,
    required super.solicitante,
    required super.pdi,
    required super.wbe,
    required super.proyectowbe,
    required super.comentario1,
    required super.comentario2,
    required super.e4e,
    required super.descripcion,
    required super.um,
    required super.m01q1,
    required super.m01q2,
    required super.m01qx,
    required super.m02q1,
    required super.m02q2,
    required super.m02qx,
    required super.m03q1,
    required super.m03q2,
    required super.m03qx,
    required super.m04q1,
    required super.m04q2,
    required super.m04qx,
    required super.m05q1,
    required super.m05q2,
    required super.m05qx,
    required super.m06q1,
    required super.m06q2,
    required super.m06qx,
    required super.m07q1,
    required super.m07q2,
    required super.m07qx,
    required super.m08q1,
    required super.m08q2,
    required super.m08qx,
    required super.m09q1,
    required super.m09q2,
    required super.m09qx,
    required super.m10q1,
    required super.m10q2,
    required super.m10qx,
    required super.m11q1,
    required super.m11q2,
    required super.m11qx,
    required super.m12q1,
    required super.m12q2,
    required super.m12qx,
    required super.cambio,
    required super.razon,
    required super.persona,
    required super.fecha,
    required super.respuesta,
    required super.razonrespuesta,
    required super.personarespuesta,
    required super.fecharespuesta,
  });

  factory SolicitadoSingle.fromList(List ls) {
    return SolicitadoSingle(
      id: ls[0].toString(),
      estado: ls[1].toString(),
      estdespacho: ls[2].toString(),
      tipo: ls[3].toString(),
      fechainicial: ls[4].toString(),
      fechacambio: ls[5].toString(),
      fechasolicitud: ls[6].toString(),
      unidad: ls[7].toString(),
      codigo: ls[8].toString(),
      proyecto: ls[9].toString(),
      circuito: ls[10].toString(),
      pm: ls[11].toString(),
      solicitante: ls[12].toString(),
      pdi: ls[13].toString(),
      wbe: ls[14].toString(),
      proyectowbe: ls[15].toString(),
      comentario1: ls[16].toString(),
      comentario2: ls[17].toString(),
      e4e: ls[18].toString(),
      descripcion: ls[19].toString(),
      um: ls[20].toString(),
      m01q1: ls[21].toString(),
      m01q2: ls[22].toString(),
      m01qx: ls[23].toString(),
      m02q1: ls[24].toString(),
      m02q2: ls[25].toString(),
      m02qx: ls[26].toString(),
      m03q1: ls[27].toString(),
      m03q2: ls[28].toString(),
      m03qx: ls[29].toString(),
      m04q1: ls[30].toString(),
      m04q2: ls[31].toString(),
      m04qx: ls[32].toString(),
      m05q1: ls[33].toString(),
      m05q2: ls[34].toString(),
      m05qx: ls[35].toString(),
      m06q1: ls[36].toString(),
      m06q2: ls[37].toString(),
      m06qx: ls[38].toString(),
      m07q1: ls[39].toString(),
      m07q2: ls[40].toString(),
      m07qx: ls[41].toString(),
      m08q1: ls[42].toString(),
      m08q2: ls[43].toString(),
      m08qx: ls[44].toString(),
      m09q1: ls[45].toString(),
      m09q2: ls[46].toString(),
      m09qx: ls[47].toString(),
      m10q1: ls[48].toString(),
      m10q2: ls[49].toString(),
      m10qx: ls[50].toString(),
      m11q1: ls[51].toString(),
      m11q2: ls[52].toString(),
      m11qx: ls[53].toString(),
      m12q1: ls[54].toString(),
      m12q2: ls[55].toString(),
      m12qx: ls[56].toString(),
      cambio: ls[57].toString(),
      razon: ls[58].toString(),
      persona: ls[59].toString(),
      fecha: ls[60].toString().length > 10
          ? DateTime.parse(ls[60].toString()).toString().substring(0, 16)
          : ls[60].toString(),
      respuesta: ls[61].toString(),
      razonrespuesta: ls[62].toString(),
      personarespuesta: ls[63].toString(),
      fecharespuesta: ls[64].toString().length > 10
          ? DateTime.parse(ls[64].toString()).toString().substring(0, 16)
          : ls[64].toString(),
    );
  }
  
   
}