import 'package:fem_app/fem/model/fem_model_single_fem.dart';
import 'package:fem_app/motor_detector_cambios/motor_detector_cambios.dart';

import '../../../resources/titulo.dart';

class EliminadosSingle extends SingleFEM {
  String cambio;
  String razon;
  String persona;
  String fecha;
  String respuesta;
  String razonrespuesta;
  String personarespuesta;
  String fecharespuesta;
  EliminadosSingle({
    required super.id,
    required super.estado,
    required super.estdespacho,
    required super.tipo,
    required super.fechainicial,
    required super.fechacambio,
    required super.fechasolicitud,
    required super.unidad,
    required super.codigo,
    required super.proyecto,
    required super.circuito,
    required super.pm,
    required super.solicitante,
    required super.pdi,
    required super.wbe,
    required super.proyectowbe,
    required super.comentario1,
    required super.comentario2,
    required super.e4e,
    required super.descripcion,
    required super.um,
    required super.m01q1,
    required super.m01q2,
    required super.m01qx,
    required super.m02q1,
    required super.m02q2,
    required super.m02qx,
    required super.m03q1,
    required super.m03q2,
    required super.m03qx,
    required super.m04q1,
    required super.m04q2,
    required super.m04qx,
    required super.m05q1,
    required super.m05q2,
    required super.m05qx,
    required super.m06q1,
    required super.m06q2,
    required super.m06qx,
    required super.m07q1,
    required super.m07q2,
    required super.m07qx,
    required super.m08q1,
    required super.m08q2,
    required super.m08qx,
    required super.m09q1,
    required super.m09q2,
    required super.m09qx,
    required super.m10q1,
    required super.m10q2,
    required super.m10qx,
    required super.m11q1,
    required super.m11q2,
    required super.m11qx,
    required super.m12q1,
    required super.m12q2,
    required super.m12qx,
    required this.cambio,
    required this.razon,
    required this.persona,
    required this.fecha,
    required this.respuesta,
    required this.razonrespuesta,
    required this.personarespuesta,
    required this.fecharespuesta,
  });

  List<ToCelda> get celdas {
    return [
      ToCelda(flex: 1, valor: e4e),
      ToCelda(flex: 4, valor: descripcion),
      ToCelda(flex: 2, valor: cambio),
      ToCelda(flex: 2, valor: razon),
      ToCelda(flex: 2, valor: persona),
      ToCelda(flex: 2, valor: fecha),
    ];
  }

  factory EliminadosSingle.fromSingleFEM(SingleFEM singleFEM) {
    return EliminadosSingle(
      id: singleFEM.id,
      estado: singleFEM.estado,
      estdespacho: singleFEM.estdespacho,
      tipo: singleFEM.tipo,
      fechainicial: singleFEM.fechainicial,
      fechacambio: singleFEM.fechacambio,
      fechasolicitud: singleFEM.fechasolicitud,
      unidad: singleFEM.unidad,
      codigo: singleFEM.codigo,
      proyecto: singleFEM.proyecto,
      circuito: singleFEM.circuito,
      pm: singleFEM.pm,
      solicitante: singleFEM.solicitante,
      pdi: singleFEM.pdi,
      wbe: singleFEM.wbe,
      proyectowbe: singleFEM.proyectowbe,
      comentario1: singleFEM.comentario1,
      comentario2: singleFEM.comentario2,
      e4e: singleFEM.e4e,
      descripcion: singleFEM.descripcion,
      um: singleFEM.um,
      m01q1: singleFEM.m01q1,
      m01q2: singleFEM.m01q2,
      m01qx: singleFEM.m01qx,
      m02q1: singleFEM.m02q1,
      m02q2: singleFEM.m02q2,
      m02qx: singleFEM.m02qx,
      m03q1: singleFEM.m03q1,
      m03q2: singleFEM.m03q2,
      m03qx: singleFEM.m03qx,
      m04q1: singleFEM.m04q1,
      m04q2: singleFEM.m04q2,
      m04qx: singleFEM.m04qx,
      m05q1: singleFEM.m05q1,
      m05q2: singleFEM.m05q2,
      m05qx: singleFEM.m05qx,
      m06q1: singleFEM.m06q1,
      m06q2: singleFEM.m06q2,
      m06qx: singleFEM.m06qx,
      m07q1: singleFEM.m07q1,
      m07q2: singleFEM.m07q2,
      m07qx: singleFEM.m07qx,
      m08q1: singleFEM.m08q1,
      m08q2: singleFEM.m08q2,
      m08qx: singleFEM.m08qx,
      m09q1: singleFEM.m09q1,
      m09q2: singleFEM.m09q2,
      m09qx: singleFEM.m09qx,
      m10q1: singleFEM.m10q1,
      m10q2: singleFEM.m10q2,
      m10qx: singleFEM.m10qx,
      m11q1: singleFEM.m11q1,
      m11q2: singleFEM.m11q2,
      m11qx: singleFEM.m11qx,
      m12q1: singleFEM.m12q1,
      m12q2: singleFEM.m12q2,
      m12qx: singleFEM.m12qx,
      cambio: '',
      razon: '',
      persona: '',
      fecha: DateTime.now().toString(),
      respuesta: '',
      razonrespuesta: '',
      personarespuesta: '',
      fecharespuesta: '',
    );
  }

  factory EliminadosSingle.fromComparison({
    required SingleFEM oldFEM,
    required SingleFEM newFEM,
  }) {
    String cambio = detectorCambios(newFEM: newFEM, oldFEM: oldFEM);
    return EliminadosSingle(
      id: oldFEM.id,
      estado: oldFEM.estado,
      estdespacho: oldFEM.estdespacho,
      tipo: oldFEM.tipo,
      fechainicial: oldFEM.fechainicial,
      fechacambio: oldFEM.fechacambio,
      fechasolicitud: oldFEM.fechasolicitud,
      unidad: oldFEM.unidad,
      codigo: oldFEM.codigo,
      proyecto: oldFEM.proyecto,
      circuito: oldFEM.circuito,
      pm: oldFEM.pm,
      solicitante: oldFEM.solicitante,
      pdi: oldFEM.pdi,
      wbe: oldFEM.wbe,
      proyectowbe: oldFEM.proyectowbe,
      comentario1: oldFEM.comentario1,
      comentario2: oldFEM.comentario2,
      e4e: oldFEM.e4e,
      descripcion: oldFEM.descripcion,
      um: oldFEM.um,
      m01q1: oldFEM.m01q1,
      m01q2: oldFEM.m01q2,
      m01qx: oldFEM.m01qx,
      m02q1: oldFEM.m02q1,
      m02q2: oldFEM.m02q2,
      m02qx: oldFEM.m02qx,
      m03q1: oldFEM.m03q1,
      m03q2: oldFEM.m03q2,
      m03qx: oldFEM.m03qx,
      m04q1: oldFEM.m04q1,
      m04q2: oldFEM.m04q2,
      m04qx: oldFEM.m04qx,
      m05q1: oldFEM.m05q1,
      m05q2: oldFEM.m05q2,
      m05qx: oldFEM.m05qx,
      m06q1: oldFEM.m06q1,
      m06q2: oldFEM.m06q2,
      m06qx: oldFEM.m06qx,
      m07q1: oldFEM.m07q1,
      m07q2: oldFEM.m07q2,
      m07qx: oldFEM.m07qx,
      m08q1: oldFEM.m08q1,
      m08q2: oldFEM.m08q2,
      m08qx: oldFEM.m08qx,
      m09q1: oldFEM.m09q1,
      m09q2: oldFEM.m09q2,
      m09qx: oldFEM.m09qx,
      m10q1: oldFEM.m10q1,
      m10q2: oldFEM.m10q2,
      m10qx: oldFEM.m10qx,
      m11q1: oldFEM.m11q1,
      m11q2: oldFEM.m11q2,
      m11qx: oldFEM.m11qx,
      m12q1: oldFEM.m12q1,
      m12q2: oldFEM.m12q2,
      m12qx: oldFEM.m12qx,
      cambio: cambio,
      razon: '',
      persona: '',
      fecha: DateTime.now().toString(),
      respuesta: '',
      razonrespuesta: '',
      personarespuesta: '',
      fecharespuesta: '',
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'estado': estado,
      'estdespacho': estdespacho,
      'tipo': tipo,
      'fechainicial': fechainicial,
      'fechacambio': fechacambio,
      'fechasolicitud': fechasolicitud,
      'unidad': unidad,
      'codigo': codigo,
      'proyecto': proyecto,
      'circuito': circuito,
      'pm': pm,
      'solicitante': solicitante,
      'pdi': pdi,
      'wbe': wbe,
      'proyectowbe': proyectowbe,
      'comentario1': comentario1,
      'comentario2': comentario2,
      'e4e': e4e,
      'descripcion': descripcion,
      'um': um,
      'm01q1': m01q1,
      'm01q2': m01q2,
      'm01qx': m01qx,
      'm02q1': m02q1,
      'm02q2': m02q2,
      'm02qx': m02qx,
      'm03q1': m03q1,
      'm03q2': m03q2,
      'm03qx': m03qx,
      'm04q1': m04q1,
      'm04q2': m04q2,
      'm04qx': m04qx,
      'm05q1': m05q1,
      'm05q2': m05q2,
      'm05qx': m05qx,
      'm06q1': m06q1,
      'm06q2': m06q2,
      'm06qx': m06qx,
      'm07q1': m07q1,
      'm07q2': m07q2,
      'm07qx': m07qx,
      'm08q1': m08q1,
      'm08q2': m08q2,
      'm08qx': m08qx,
      'm09q1': m09q1,
      'm09q2': m09q2,
      'm09qx': m09qx,
      'm10q1': m10q1,
      'm10q2': m10q2,
      'm10qx': m10qx,
      'm11q1': m11q1,
      'm11q2': m11q2,
      'm11qx': m11qx,
      'm12q1': m12q1,
      'm12q2': m12q2,
      'm12qx': m12qx,
      'cambio': cambio,
      'razon': razon,
      'persona': persona,
      'fecha': fecha,
      'respuesta': respuesta,
      'razonrespuesta': razonrespuesta,
      'personarespuesta': personarespuesta,
      'fecharespuesta': fecharespuesta,
    };
  }

  factory EliminadosSingle.fromList(List ls) {
    return EliminadosSingle(
      id: ls[0].toString(),
      estado: ls[1].toString(),
      estdespacho: ls[2].toString(),
      tipo: ls[3].toString(),
      fechainicial: ls[4].toString(),
      fechacambio: ls[5].toString(),
      fechasolicitud: ls[6].toString(),
      unidad: ls[7].toString(),
      codigo: ls[8].toString(),
      proyecto: ls[9].toString(),
      circuito: ls[10].toString(),
      pm: ls[11].toString(),
      solicitante: ls[12].toString(),
      pdi: ls[13].toString(),
      wbe: ls[14].toString(),
      proyectowbe: ls[15].toString(),
      comentario1: ls[16].toString(),
      comentario2: ls[17].toString(),
      e4e: ls[18].toString(),
      descripcion: ls[19].toString(),
      um: ls[20].toString(),
      m01q1: ls[21].toString(),
      m01q2: ls[22].toString(),
      m01qx: ls[23].toString(),
      m02q1: ls[24].toString(),
      m02q2: ls[25].toString(),
      m02qx: ls[26].toString(),
      m03q1: ls[27].toString(),
      m03q2: ls[28].toString(),
      m03qx: ls[29].toString(),
      m04q1: ls[30].toString(),
      m04q2: ls[31].toString(),
      m04qx: ls[32].toString(),
      m05q1: ls[33].toString(),
      m05q2: ls[34].toString(),
      m05qx: ls[35].toString(),
      m06q1: ls[36].toString(),
      m06q2: ls[37].toString(),
      m06qx: ls[38].toString(),
      m07q1: ls[39].toString(),
      m07q2: ls[40].toString(),
      m07qx: ls[41].toString(),
      m08q1: ls[42].toString(),
      m08q2: ls[43].toString(),
      m08qx: ls[44].toString(),
      m09q1: ls[45].toString(),
      m09q2: ls[46].toString(),
      m09qx: ls[47].toString(),
      m10q1: ls[48].toString(),
      m10q2: ls[49].toString(),
      m10qx: ls[50].toString(),
      m11q1: ls[51].toString(),
      m11q2: ls[52].toString(),
      m11qx: ls[53].toString(),
      m12q1: ls[54].toString(),
      m12q2: ls[55].toString(),
      m12qx: ls[56].toString(),
      cambio: ls[57].toString(),
      razon: ls[58].toString(),
      persona: ls[59].toString(),
      fecha: ls[60].toString().length > 10
          ? DateTime.parse(ls[60].toString()).toString().substring(0, 16)
          : ls[60].toString(),
      respuesta: ls[61].toString(),
      razonrespuesta: ls[62].toString(),
      personarespuesta: ls[63].toString(),
      fecharespuesta: 
      ls[64].toString().length > 10
          ? DateTime.parse(ls[64].toString()).toString().substring(0, 16)
          : ls[64].toString(),
    );
  }

  @override
  List<String> toList(){
    return [
      id,
      estado,
      estdespacho,
      tipo,
      fechainicial,
      fechacambio,
      fechasolicitud,
      unidad,
      codigo,
      proyecto,
      circuito,
      pm,
      solicitante,
      pdi,
      wbe,
      proyectowbe,
      comentario1,
      comentario2,
      e4e,
      descripcion,
      um,
      m01q1,
      m01q2,
      m01qx,
      m02q1,
      m02q2,
      m02qx,
      m03q1,
      m03q2,
      m03qx,
      m04q1,
      m04q2,
      m04qx,
      m05q1,
      m05q2,
      m05qx,
      m06q1,
      m06q2,
      m06qx,
      m07q1,
      m07q2,
      m07qx,
      m08q1,
      m08q2,
      m08qx,
      m09q1,
      m09q2,
      m09qx,
      m10q1,
      m10q2,
      m10qx,
      m11q1,
      m11q2,
      m11qx,
      m12q1,
      m12q2,
      m12qx,
      cambio,
      razon,
      persona,
      fecha,
      respuesta,
      razonrespuesta,
      personarespuesta,
    ];
  }
}
